language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"
    - web/node_modules

env:
  - PLATFORMIO_ENV=esp12e
  - PLATFORMIO_ENV=esp12e_160
  - PLATFORMIO_ENV=nodemcuv2

install:
  # PlatformIO
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  - platformio update
  - platformio lib install
  # install node
  - nvm install node
  - cd web && npm install && cd ..

script:
  - platformio run --environment=$PLATFORMIO_ENV
  - scripts/stylecheck
  - git diff --exit-code
